### Application version ###
applicationVersion=0.0.1-SNAPSHOT

### Project configs ###
projectGroup=io.dodn.springboot

### Project dependency versions ###
kotlinVersion=2.3.21
javaVersion=25

### Plugin dependency versions ###
asciidoctorConvertVersion=4.0.5
ktlintVersion=14.2.0

### Spring dependency versions ###
springBootVersion=4.1.0
springDependencyManagementVersion=1.1.7
springCloudDependenciesVersion=2025.1.2

### External dependency versions ###
springMockkVersion=5.0.1
sentryVersion=8.43.2
